### ISSUE TITLE
Custom Analysis with single type produces warnings for other types

### ISSUE THREAD

**Issue by YakupIpek21** [mrlacey/Rapid-XAML-Toolkit#507] opened 2022-02-11 11:28 UTC
**Describe the bug**
Having generated a Custom Analyzer for a single type let's say type **TextBlock**, then the analyzer also produces a warning for the **Grid** tag.

**To Reproduce**

1. Generate a custom analyzer for type **TextBlock**
2. Create a wpf project (.net core 3.1) and add the project containing the custom analyzer as a reference
3. In a xaml file add a grid tag containing a **textblock** tag
4. Trigger the analysis by saving the xaml file, warning is produced for both **grid** and **textblock**

**Expected behavior**
Only the **TextBlock** should be affected.

**Additional context**
Newest version (0.13.2) of the RapidXaml.Analysis extension is installed

**Comment by mrlacey** [comment] 2022-02-11 15:17
Is this a duplicate of #506 ?

---

The warnings you are describing for the `Grid` and `TextBlock` sound like the ones that are from the built-in analyzers.
I full list of all warnings/analyzers that are included by default can be found [here](https://github.com/mrlacey/Rapid-XAML-Toolkit/blob/main/docs/warnings/readme.md#rapid-xaml-toolkit---warnings).

If you don't want these to be included in the output, you can prevent them from being shown by [adding a settings file that changes the output for these error codes to be "NONE"](https://github.com/mrlacey/Rapid-XAML-Toolkit/blob/main/docs/configuring-analysis.md#changing-errortype).
If you want to disable all the built-in analyzers, it currently requires specifying a "NONE" value for each of the codes. I have a [separate issue](https://github.com/mrlacey/Rapid-XAML-Toolkit/issues/330) for making that easier. Please comment if you have a good reason for raising the priority of that work.

**Comment by YakupIpek21** [comment] 2022-02-11 15:38
It was somehow related to [#506 ](https://github.com/mrlacey/Rapid-XAML-Toolkit/issues/506), but I can not manage to reproduce the behaviour again.

**Closed as completed** 2022-02-24 15:17 UTC
Labels: bug
