### ISSUE TITLE
Build rxt.dev.ci_20190401.427440 failed

### ISSUE THREAD

**Issue by wasteam** [mrlacey/Rapid-XAML-Toolkit#160] opened 2019-04-01 12:35 UTC
## Build rxt.dev.ci_20190401.427440
- **Build result:** `failed`
- **Build queued:** 4/1/2019 12:31:30 PM
- **Build duration:** 4.07 minutes
### Details
Build [rxt.dev.ci_20190401.427440](https://winappstudio.visualstudio.com/web/build.aspx?pcguid=a4ef43be-68ce-4195-a619-079b4d9834c2&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f27440) failed

+ Error: The process 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe' failed with exit code 1
+ VsTest task failed.

Find detailed information in the [build log files](https://uwpctdiags.blob.core.windows.net/buildlogs/rxt.dev.ci_20190401.427440_logs.zip)

**Comment by mrlacey** [comment] 2019-04-01 12:38
dupe of #159

**Closed as completed by mrlacey** 2019-04-01 12:38 UTC
Labels: bug
