### ISSUE TITLE
NullreferenceException when opening XAML file (Xamarin.Forms)

### ISSUE THREAD

**Issue by MagicAndre1981** [mrlacey/Rapid-XAML-Toolkit#340] opened 2020-04-21 08:54 UTC
**Describe the bug**

When I open a XAML file I get a message from VS telling that a NullreferenceException happened.

![vs2019_nre](https://user-images.githubusercontent.com/8274816/79848865-f4f75c80-83c1-11ea-964f-c0e40b357b77.png)

**To Reproduce**

1. Open XAML file
2. See error

**Expected behavior**

page opens without any issues.

**Additional context**

Here is stack from `ActivityLog.xml`

> System.NullReferenceException: Object reference not set to an instance of an object. 
> at RapidXamlToolkit.XamlAnalysis.Tags.RapidXamlDisplayedTag.TryGetConfiguredErrorType(String errorCode, TagErrorType& tagErrorType) 
> at RapidXamlToolkit.XamlAnalysis.Tags.RapidXamlDisplayedTag.get_ConfiguredErrorType()
> at RapidXamlToolkit.XamlAnalysis.Tags.RapidXamlDisplayedTag.AsErrorRow() 
> at RapidXamlToolkit.XamlAnalysis.RapidXamlTagger.OnXamlDocParsed(Object sender, RapidXamlParsingEventArgs e) 
> at RapidXamlToolkit.XamlAnalysis.RapidXamlTagger..ctor(ITextBuffer buffer, String file) 
> at RapidXamlToolkit.XamlAnalysis.RapidXamlTagProvider.<>c__DisplayClass4_0`1.<CreateTagger>b__0() 
> at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator) 
> at RapidXamlToolkit.XamlAnalysis.RapidXamlTagProvider.CreateTagger[T](ITextBuffer buffer) 
> at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.InstantiateBuferTagger(Lazy`2 factory, ITextBuffer textBuffer, IList`1 newTaggers) --- End of stack trace from previous location where exception was thrown ---  
> at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

VS2019 16.4.6
Xamarin.Forms 4.5.0.617

**Comment by mrlacey** [comment] 2020-04-21 09:29
@MagicAndre1981 Thanks for reporting this.
Is it just with one file, or any file in the project?
If just one file, can you share a copy of the XAML file? This may help me reproduce the issue.

**Comment by MagicAndre1981** [comment] 2020-04-21 09:38
not always, but always for this project I got from syncfusion support

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Forms.Views.Dashboard"
             xmlns:controls="clr-namespace:Forms.Controls;assembly=Forms"
             xmlns:chart="clr-namespace:Syncfusion.SfChart.XForms;assembly=Syncfusion.SfChart.XForms"
             xmlns:border="clr-namespace:Syncfusion.XForms.Border;assembly=Syncfusion.Core.XForms"
             xmlns:buttons="clr-namespace:Syncfusion.XForms.Buttons;assembly=Syncfusion.Buttons.XForms"
             xmlns:viewModel="clr-namespace:Forms.ViewModels.Dashboard"
             xmlns:listView="clr-namespace:Syncfusion.ListView.XForms;assembly=Syncfusion.SfListView.XForms"
             x:Class="Forms.Views.Dashboard.HealthCarePage"
             xmlns:cards="clr-namespace:Syncfusion.XForms.Cards;assembly=Syncfusion.Cards.XForms"
             xmlns:gradient="clr-namespace:Syncfusion.XForms.Graphics;assembly=Syncfusion.Core.XForms"
             xmlns:behavior ="clr-namespace:Forms.Behaviors;assembly=Forms"
             x:Name="healthCarePage"
             NavigationPage.HasNavigationBar="False"
             Style="{StaticResource ContentPageStyle}">

    <ContentPage.BindingContext>
        <viewModel:HealthCareViewModel />
    </ContentPage.BindingContext>

    <ContentPage.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Styles.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </ContentPage.Resources>

    <ContentPage.ControlTemplate>
        <ControlTemplate>
            <StackLayout x:Name="rootLayout" Spacing="10">

                <!--  Title View  -->
                <controls:TitleView
                    Title="Health Care"
                    FontFamily="{StaticResource Montserrat-Medium}"
                    FontSize="16">
                    <controls:TitleView.LeadingView>

                        <buttons:SfButton
                            Command="{TemplateBinding BindingContext.menuCommand}"
                            CornerRadius="4"
                            HorizontalOptions="Start"
                            Style="{StaticResource IconButtonStyle}"
                            Text="{StaticResource Menu}" />

                    </controls:TitleView.LeadingView>

                    <controls:TitleView.TrailingView>

                        <border:SfBorder
                            BackgroundColor="{DynamicResource Gray-200}"
                            BorderColor="{DynamicResource Gray-White}"
                            Style="{StaticResource ProfileBorderStyle}">
                            <Image HeightRequest="40" WidthRequest="40">
                                <Image.Source>
                                    <UriImageSource
                                        CacheValidity="14"
                                        CachingEnabled="true"
                                        Uri="{Binding Path=BindingContext.ProfileImage, Source={x:Reference healthCarePage}}" />
                                </Image.Source>
                            </Image>
                        </border:SfBorder>

                    </controls:TitleView.TrailingView>
                </controls:TitleView>

                <ContentPresenter />

            </StackLayout>
        </ControlTemplate>
    </ContentPage.ControlTemplate>

    <ContentPage.Content>
        <ScrollView>
            <StackLayout Spacing="0" Margin="0" Padding="8">
                <listView:SfListView SelectionMode="None" AutoFitMode="Height" ItemSpacing="8" ItemsSource="{Binding CardItems}">

                    <listView:SfListView.ItemTemplate>
                        <DataTemplate>

                            <cards:SfCardView CornerRadius="8">
                                <cards:SfCardView.Content>
                                    <Grid>

                                        <gradient:SfGradientView>
                                            <gradient:SfGradientView.BackgroundBrush>
                                                <gradient:SfLinearGradientBrush>
                                                    <gradient:SfLinearGradientBrush.GradientStops>
                                                        <gradient:SfGradientStop Color="{Binding BackgroundGradientStart}" Offset="0.0"/>
                                                        <gradient:SfGradientStop Color="{Binding BackgroundGradientEnd}" Offset="1.0"/>
                                                    </gradient:SfLinearGradientBrush.GradientStops>
                                                </gradient:SfLinearGradientBrush>
                                            </gradient:SfGradientView.BackgroundBrush>
                                        </gradient:SfGradientView>

                                        <StackLayout Margin="15" Spacing="5">
                                            <Label TextColor="{DynamicResource Gray-White}" LineHeight="{OnPlatform Android=1.25, Default=-1}" FontFamily="{StaticResource Montserrat-SemiBold}" FontSize="12" Text="{Binding Category}"></Label>
                                            <Label TextColor="{DynamicResource Gray-White}" LineHeight="{OnPlatform Android=1.25, Default=-1}" FontFamily="{StaticResource Montserrat-SemiBold}" FontSize="24" Text="{Binding CategoryValue}"></Label>
                                            <chart:SfChart BackgroundColor="Transparent"
                                                Margin="0, 11, 0, 0"
                                                HeightRequest="{OnIdiom Phone=44, Desktop=80, Tablet=80}"
                                                HorizontalOptions="FillAndExpand"
                                                VerticalOptions="FillAndExpand">
                                        <chart:SfChart.PrimaryAxis>
                                            <chart:DateTimeAxis ShowMajorGridLines="False" RangePadding="None" IsVisible="False"/>
                                        </chart:SfChart.PrimaryAxis>

                                        <chart:SfChart.SecondaryAxis>
                                            <chart:NumericalAxis ShowMajorGridLines="False" IsVisible="False" />
                                        </chart:SfChart.SecondaryAxis>

                                        <chart:SfChart.Series>
                                            <chart:SplineSeries
                                                        ItemsSource="{Binding ChartData, Mode=TwoWay}"
                                                        Color="{DynamicResource Gray-White}"
                                                        StrokeWidth="2"
                                                        XBindingPath="XValue"
                                                        YBindingPath="YValue" />
                                        </chart:SfChart.Series>

                                    </chart:SfChart>
                                        </StackLayout>
                                    </Grid>
                                </cards:SfCardView.Content>
                            </cards:SfCardView>

                        </DataTemplate>
                    </listView:SfListView.ItemTemplate>

                    <!--  Layout to customize number of columns in SfListView  -->
                    <listView:SfListView.LayoutManager>
                        <listView:GridLayout SpanCount="2" />
                    </listView:SfListView.LayoutManager>

                    <listView:SfListView.Behaviors>
                        <behavior:SfListViewExtendHeightBehavior ></behavior:SfListViewExtendHeightBehavior>
                    </listView:SfListView.Behaviors>

                </listView:SfListView>

                <listView:SfListView SelectionMode="None" ItemSpacing="8" ItemSize="80" ItemsSource="{Binding ListItems}">
                    <listView:SfListView.ItemTemplate>
                        <DataTemplate>

                            <cards:SfCardView CornerRadius="4" IndicatorColor="{Binding BackgroundGradientStart}" IndicatorPosition="Left" IndicatorThickness="8">
                                <Grid RowSpacing="4" Padding="16">
                                    <Label Text="{Binding Category}" Style="{StaticResource LabelStyle}"></Label>
                                    <Label Grid.Column="1" Grid.RowSpan="2" FontSize="16" Style="{StaticResource LabelStyle}" HorizontalOptions="EndAndExpand" VerticalOptions="Center" Text="{Binding CategoryValue}"></Label>
                                    <Label Grid.Row="1" Text="{Binding CategoryPercentage}" FontSize="12" TextColor="{DynamicResource Gray-700}" Style="{StaticResource LabelStyle}" FontFamily="{StaticResource Montserrat-Medium}"></Label>
                                </Grid>

                            </cards:SfCardView>

                        </DataTemplate>
                    </listView:SfListView.ItemTemplate>

                </listView:SfListView>
            </StackLayout>
        </ScrollView>
    </ContentPage.Content>

</ContentPage>

```

**Comment by mrlacey** [comment] 2020-04-21 12:05
Investigating with the solution from https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms

**Comment by mrlacey** [comment] 2020-04-26 16:28
hopefully this is fixed in 0.9.3 which has just been released

**Comment by MagicAndre1981** [comment] 2020-04-27 07:44
> hopefully this is fixed in 0.9.3

I no longer get the message with that XAML file from syncfusion support, but Visual Studio is freezing. I get the message that VS is busy while scrolling and typing inside that XAML.

Removing RapidXAML fixes the VS hang.

**Comment by mrlacey** [comment] 2020-04-27 11:11
> I no longer get the message with that XAML file from syncfusion support, but Visual Studio is freezing. I get the message that VS is busy while scrolling and typing inside that XAML.
> 
> Removing RapidXAML fixes the VS hang.

The extension only does things when a file is opened or saved. It shouldn't impact scrolling or typing.
Do you get the Yellow bar at the top of the screen saying it's the cause of the problem?

It shouldn't matter but, which version of Visual Studio are you using?

**Comment by MagicAndre1981** [comment] 2020-04-27 14:44
> The extension only does things when a file is opened or saved. It shouldn't impact scrolling or typing.
> Do you get the Yellow bar at the top of the screen saying it's the cause of the problem?

I opened the syncfusion solution and accidently used mouse wheel to scroll, so the VS scrolled, at half page, the scrolling stopped and when I click inside VS, I got the message that VS is busy.

> It shouldn't matter but, which version of Visual Studio are you using?

[VS2019 16.4.7](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.4#16.4.7)

**Comment by mrlacey** [comment] 2020-04-28 11:51
I've found that the Essential UI kit project can be very slow to load, but once it (and VS) has finished loading everything I don't experience the issues you report.

Some things to try:

Make sure: **Enable Custom Analysis** is set to false

![image](https://user-images.githubusercontent.com/189547/80483753-7fa20380-894e-11ea-9a0d-515b6af7c883.png)

Check that Visual Studio has finished loading all extensions and background processes, by clicking the button in the bottom left corner of the screen.

![image](https://user-images.githubusercontent.com/189547/80484017-f0492000-894e-11ea-8328-5245f580651c.png)

**Comment by MagicAndre1981** [comment] 2020-06-08 12:55
I'll test this tomorrow. Today I got a message from VS2019 telling me your extension caused hang:

![Rapid_XAML_VS2019_warning](https://user-images.githubusercontent.com/8274816/84032799-25a64c00-a998-11ea-8b45-b44833dce55b.png)

**Comment by mrlacey** [comment] 2020-06-08 13:15
> I'll test this tomorrow. 

👍 

> Today I got a message from VS2019 telling me your extension caused hang:
> 
> ![Rapid_XAML_VS2019_warning](https://user-images.githubusercontent.com/8274816/84032799-25a64c00-a998-11ea-8b45-b44833dce55b.png)

😢 Do you know what you were doing when this happened?

**Comment by MagicAndre1981** [comment] 2020-06-08 13:38
>  Do you know what you were doing when this happened?

I scrolled inside a XAML after opening a project.

**Comment by MagicAndre1981** [comment] 2020-07-01 06:52
With 0.10 it is fixed. I no longer get the message about delay/not responding and scrolling works fine

**Comment by mrlacey** [comment] 2020-07-02 08:56
> With 0.10 it is fixed. I no longer get the message about delay/not responding and scrolling works fine

0.10 includes a number of changes, fixes, and optimizations internally that will have helped to fixing/avoiding this issue. Thanks for letting me know this is no longer a problem for you. :)

**Closed as completed by mrlacey** 2020-07-02 08:56 UTC
Labels: bug, XAML-Analysis
